# Generated by Django 4.2.17 on 2024-12-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteclipper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=15)),
                ('pos', models.BooleanField()),
            ],
        ),
    ]
